export const CHANGE_FILTER_YEAR = 'CHANGE_FILTER_YEAR';
export const CHANGE_FILTER_NAME = 'CHANGE_FILTER_NAME';
export const GET_MOVIES_LIST = 'GET_MOVIES_LIST';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
export const GET_TOTAL_PAGES = 'GET_TOTAL_PAGES';
export const CHANGE_CURRENT_PAGE = 'CHANGE_PAGE';
